---

- name: add java apt repository
  apt_repository: 
    repo: 'ppa:openjdk-r/ppa' 
    state: present 
    filename: openjdk-7-jdk
    update_cache: yes

- name: install openjdk7
  apt: 
    name: openjdk-7-jdk
    state: present
    update_cache: yes

- name: install zip and unzip
  become: true
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
    - zip
    - unzip

- name: Download JBoss from jboss.org
  get_url:
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
    dest: /opt/jboss-as-7.1.1.Final.zip


- name: Extract archive
  unarchive:
    dest: /usr/share
    src: /opt/jboss-as-7.1.1.Final.zip
    creates: /usr/share/jboss-as
    copy: no

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: /bin/mv jboss-as-7.1.1.Final jboss-as 
  args:
    chdir: /usr/share 
    creates: /usr/share/jboss-as


- name: download the jboss module
  get_url:
    url: http://repo1.maven.org/maven2/org/jboss/modules/jboss-modules/1.1.5.GA/jboss-modules-1.1.5.GA.jar
    dest: /opt/jboss-modules-1.1.5.GA.jar

- name: rename jboss module
  command: /bin/mv jboss-modules-1.1.5.GA.jar jboss-modules.jar
  args:
    chdir: /opt
    creates: /opt/jboss-modules.jar

- name: copy jboss module
  copy:
      src: /opt/jboss-modules.jar
      dest: /usr/share/jboss-as
      remote_src: yes

- name: Copying standalone.xml configuration file
  template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/


- name: run jboss standalone
  command: /usr/share/jboss-as/bin/standalone.sh &
  become: true
